name: Survival-RPG
version: 1.0
description: This plugin add some things like a RPG mod
authors: [danizml, TonimatasMC]

main: survivalrpg.SurvivalRPG

commands:
  rpg:
    description: Primary command.