name: Survival-RPG
version: 1.0.0
description: This plugin add some things like a RPG mod
author: danizml

main: survivalrpg.SurvivalRPG

commands:
  rpg:
    description: Primary command.
  rpgs:
    description: Primary command.
  warp:
    description: Warps for player.
  setwarp:
    description: Set a warp.
  delwarp:
    description: Remove a warp.

permissions:
  survivalrpg.reload:
    description: Reload the plugin config
    default: false


  survivalrpg.help:
    description: Show the plugin help
    default: false
